import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navigation from '@/components/Navigation'
import ApolloProvider from '@/providers/ApolloProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloProvider>
      <html lang="en">
        <body
          className={`${inter.className} mx-auto my-0 h-screen max-w-7xl bg-gray-900 px-4 pt-6 md:pr-0`}
        >
          <header className="px-0 md:pl-0 md:pr-4">
            <Navigation />
          </header>
          <main className="h-[calc(100vh_-_14rem)] max-h-screen items-center overflow-visible pl-4 md:h-[calc(100vh_-_4.5rem)]">
            {children}
          </main>
        </body>
      </html>
    </ApolloProvider>
  )
}
